### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by c0d3rman** [chopshop-166/wpilib-mirror#1]
This is not updated to the latest wpilib release, which has breaking changes.

**Comment by msoucy** [comment]
Got it - I hadn't seen the update yet, I'm updating now.

**Comment by c0d3rman** [comment]
Thanks! It's just our Travis builds with the new version was failing.

**Comment by msoucy** [comment]
I understand, thanks for calling attention to it. It should be up in around half an hour (some network issues)

**Comment by msoucy** [comment]
I pulled your changes into this repo - sorry about the hassle, I ran into a little issue.
